### ISSUE TITLE
RTL/align to right doesn't work since last version

### ISSUE THREAD

**Issue by liloo29** [Automattic/simplenote-macos#198]
I'm a simplenote user on mac, and writing in Hebrew (Right to Left), since version 1.3.1 the text is always align to the left no matter what I do. so for now I'm staying with the old version.

I really hope someone will fix that.

Thank you
I love Simplenote!
Liav

**Comment by roundhill** [comment]
Hi @liloo29! It appears to be working properly in the editor for RTL for me, can you provide any more details of the issue?

**Comment by liloo29** [comment]
it's simply doesn't align to the right. the direction (rtl) is ok in the last version (1.3.2) but not aligning to right. (see attached pic).
![screen shot 2018-04-14 at 0 40 45](https://user-images.githubusercontent.com/27154710/38759116-e0dc2086-3f7c-11e8-8c04-ad1d340ce22a.png)

**Comment by roundhill** [comment]
Which language do you have set in the macOS system settings for `Language & Region?`

**Comment by liloo29** [comment]
English and Hebrew. anyway in version 1.2 it works great, and align to the right.

**Comment by edequalsawesome** [comment]
Issue also reported in #1687028-zen

**Comment by liloo29** [comment]
English for primary, and than Hebrew

**Comment by jleandroperez** [comment]
I'm sorry it took us so long to ship proper RTL support.

As per Simplenote 1.12 (due out later this month), this issue should be fixed. Screenshot below!

Please feel free to reopen if needed, thank you!!

<img width="600" alt="Screen Shot 2020-07-03 at 12 38 33 PM 1" src="https://user-images.githubusercontent.com/1195260/86483296-211c4b80-bd2a-11ea-9b0b-29e05d71922d.png">

**Comment by erricgunawan** [comment]
I'm reopening the issue since we have a report from a 3-star MacOS app review:

> The app doesn't support RTL (Right-to-left) such as Arabic languages properly.

I'm hoping we can get more info on the issues if they reached out to us. If we didn't hear, or there is no other report, I guess we can then close this again? 

#### Version 2.17 | Jan 21, 2022

**Comment by liloo29** [comment]
Yes there is still a problem. Cant make the text align to the right on mac
os.
I wish it will be fixed.
Thank you
